import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import FloatingSidebar from "@/components/ui/FloatingSidebar"; // 🧠 Tambahkan ini

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${ptSans.variable} antialiased relative`}
      >
        <FloatingSidebar /> {/* ✅ Sidebar muncul di depan konten */}

        {/* ⬇️ Beri padding agar konten tidak ketumpuk sidebar */}
      
          {children}

      </body>
    </html>
  );
}
